// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfCv3gdpD-jWCYe1oekhcuU2xkpIWywoc',
    appId: '1:755396711163:web:07cbed82786ec87858165e',
    messagingSenderId: '755396711163',
    projectId: 'todo-app-by-saad',
    authDomain: 'todo-app-by-saad.firebaseapp.com',
    storageBucket: 'todo-app-by-saad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChfP1c54YITodMmsuM0ZRcNLsQFaQKSus',
    appId: '1:755396711163:android:f3604275d8bcfcfb58165e',
    messagingSenderId: '755396711163',
    projectId: 'todo-app-by-saad',
    storageBucket: 'todo-app-by-saad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgcFsib9AHuxnx91GiA4WOOXNHJA7vUn8',
    appId: '1:755396711163:ios:670485dbfcb9ef9f58165e',
    messagingSenderId: '755396711163',
    projectId: 'todo-app-by-saad',
    storageBucket: 'todo-app-by-saad.appspot.com',
    iosBundleId: 'com.example.mytodoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgcFsib9AHuxnx91GiA4WOOXNHJA7vUn8',
    appId: '1:755396711163:ios:490f031b813aea0958165e',
    messagingSenderId: '755396711163',
    projectId: 'todo-app-by-saad',
    storageBucket: 'todo-app-by-saad.appspot.com',
    iosBundleId: 'com.example.mytodoapp.RunnerTests',
  );
}
